### ISSUE TITLE
Angular templates compilation

### ISSUE THREAD

**Issue by moff** [Vivify-Ideas/Laravel5-Angular2-Material#1]
Hey, guys! @nikolasp @goranprijic @milosh012 

It's nice to see new boilerplate designed for Angular 2 based apps. Just wanted to play around it a bit and noticed that I can use only inline templates which isn't a clean solution in terms of code separation.
Have I missed something and doing wrong or there is no such feature so far? 

P.S. I think I have an idea how to implement this feature =)

**Comment by moff** [comment]
Ok, I solved this by using https://github.com/laxa1986/gulp-angular-embed-templates

But I had to fork and rewrite a bit https://github.com/moff/laravel-elixir-webpack-ex that used in the boilerplate...  to add a pipe for using it with Elixir webpack extension.

Here is how I implemented it in a boilerplate fork: https://github.com/moff/Laravel5-Angular2-Material/commit/6b53330909939e4deea5b9c157dc356d2b8758e5

Funny thing that I found 2nd solution to template embedding after coding the 1st one above, and it doesn't require any coding (facepalm)

It's just about moving HTML to a separate ts-file (e.g. test.template.ts) which just exports a string:
```
export const template = `
    <h3>this is test component template parsed</h3>
    <div class="test">Yes, I'm test, {{name}}</div>
`;
```
and importing it in a component:
```
import {Component} from '@angular/core';
import {template} from './test.template';
@Component({
    selector: "test-cmp",
    template: template
})
export class TestComponent {}
```

That solution separates code and syntax highlighting works, but maybe it's not the cleanest solution.

Let me know what you think.

**Comment by nikolasp** [comment]
Hi @moff 

I've finally found time to check this. Your first solution is also good, but I think that this solution is slightly better 99929f2b6e1b146a6363dc40f8305f1165e746b2. Only global typing require is added and loader for html files is now raw-loader, so you can use require for html files.

**Comment by moff** [comment]
Hi @nikolasp 

Your solution is way better, thanks for sharing! =)
